import { test, expect } from '@playwright/test';

test('orbit the station and extinguish the fire with the roof hose', async ({page}) => {
  test.setTimeout(120000);
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.route('https://fonts.googleapis.com/**', route => route.abort());
  await page.goto('/', {waitUntil:'domcontentloaded'});
  await page.getByRole('button',{name:'START EXPLORING'}).click({timeout:60000});
  await expect(page.locator('.loader')).toHaveClass(/departed/);
  const status = page.locator('.water-status');
  await expect(status).toHaveAttribute('data-state', 'extinguished', {timeout:60000});
  await expect(page.locator('#water')).toHaveAttribute('aria-pressed','false');
  await page.getByRole('button', {name:'Replay fire extinguishing', exact:true}).click();
  await expect(status).toHaveAttribute('data-state', 'extinguished', {timeout:60000});
  const before = await page.locator('#spot-about').getAttribute('style');
  const viewport = page.viewportSize();
  await page.mouse.move(viewport.width * .4, viewport.height * .7);
  await page.mouse.down();
  await page.mouse.move(viewport.width * .8, viewport.height * .7, {steps:15});
  await page.mouse.up();
  await expect.poll(() => page.locator('#spot-about').getAttribute('style')).not.toBe(before);
  await page.getByRole('button', {name:'Reset camera'}).click();
  await page.getByRole('button', {name:'Toggle 360 degree view'}).click();
  await expect(page.getByRole('button', {name:'Toggle 360 degree view'})).toHaveAttribute('aria-pressed','true');
  await page.getByRole('button', {name:'Reset camera'}).click();
  await expect(page.getByRole('button', {name:'Toggle 360 degree view'})).toHaveAttribute('aria-pressed','false');
  await expect(page.locator('#scene canvas')).toBeVisible();
  expect(errors).toEqual([]);
  await page.screenshot({path:`water-${test.info().project.name}.png`});
});
